language: elixir
os:
  - linux
elixir:
  - 1.3.4
otp_release:
  - 19.1
  - 18.3
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq p7zip-full
script:
  - mix test --trace
env:
  - MIX_ENV=test
branches:
  only:
    - master
